name: 'Mediawiki Extension PHPUnit Runner'
description: 'Setups MediaWiki and runs PHPUnit test for an extension'
author: 'WikiTeq'
branding:
  color: yellow
  icon: book-open
inputs:
  php:
    description: 'PHP version'
    required: true
  mwbranch:
    description: 'Mediawiki branch to test against'
    required: true
  extension:
    description: 'Extension name to test'
    required: true
  type:
    description: 'Is it an extension or skin'
    required: false
    default: 'extension'
  extra_file:
    description: 'Path relative to the extension for a PHP file to load in settings'
    required: false
    default: ''
  use_mysql:
    description: Use MySQL instead of SQLite
    required: false
    default: false
  dependencies:
    description: JSON encoded array of dependencies to pass to checkouts
    required: false
    default: '[]'
runs:
  using: 'composite'
  steps:

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php }}
        extensions: ${{ env.PHP_EXTENSIONS }}
        tools: composer:2.1.14
      env:
        PHP_EXTENSIONS: ${{ inputs.use_mysql && 'mbstring, intl, mysqli' || 'mbstring, intl' }}

    - name: Add Composer cache
      uses: actions/cache@v2
      with:
        path: ~/.composer/cache
        key: composer-php${{ inputs.php }}

    - name: Download Mediawiki
      uses: actions/checkout@v2
      with:
        path: mediawiki
        repository: wikimedia/mediawiki
        ref: ${{ inputs.mwbranch }}

    - name: Install MediaWiki
      run: bash $GITHUB_ACTION_PATH/install.sh ${{ inputs.extension }} ${{ inputs.type }} ${{ inputs.use_mysql }} ${{ inputs.extra_file }}
      shell: bash

    - uses: actions/checkout@v2
      with:
        path: mediawiki/${{ inputs.type }}s/${{ inputs.extension }}

    - name: Install dependencies
      uses: ./dependency-action
      with:
        dependencies: ${{ inputs.dependencies }}

    - name: Composer updates
      working-directory: mediawiki
      run: composer update
      shell: bash

    - name: Run updates
      working-directory: mediawiki
      run: php maintenance/update.php --quick
      shell: bash

    - name: Run PHPUnit
      working-directory: mediawiki
      run: php tests/phpunit/phpunit.php --testsuite extensions --exclude-group Broken,ParserFuzz,Stub
      shell: bash
